all: long1 long2 long3 long4 long5 long6

long1:
	gcc -o long1 longLoop.c

long2:
	gcc -o long2 longLoop.c

long3:
	gcc -o long3 longLoop.c

long4:
	gcc -o long4 longLoop.c

long5:
	gcc -o long5 longLoop.c

long6:
	gcc -o long6 longLoop.c

clean:
	rm -f *.o domake

